name: directory_bookmarks
description: A Flutter plugin for cross-platform directory bookmarking and file operations
version: 0.1.0
homepage: https://github.com/yourusername/directory_bookmarks

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.directory_bookmarks
        pluginClass: DirectoryBookmarksPlugin
      macos:
        pluginClass: DirectoryBookmarksPlugin
