name: directory_bookmarks
description: A Flutter plugin for cross-platform directory bookmarking and secure file operations. Currently supports macOS security-scoped bookmarks, with Android support in development.
version: 0.1.0
homepage: https://github.com/queiul/directory_bookmarks
repository: https://github.com/queiul/directory_bookmarks
issue_tracker: https://github.com/queiul/directory_bookmarks/issues
documentation: https://github.com/queiul/directory_bookmarks/blob/main/README.md

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  file_picker: ^5.5.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DirectoryBookmarksPlugin
      android:
        package: com.example.directory_bookmarks
        pluginClass: DirectoryBookmarksPlugin

topics:
  - files
  - storage
  - directory
  - bookmarks
  - security
